name: Svelte Kit Integration

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    Svelte_Kit_Unit_Tests:
        strategy:
            matrix:
                node-version: [16.x]

        runs-on: ubuntu-22.04

        steps:
            - name: Go To Working Directory
              uses: actions/checkout@v3
            - name: Setups Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Restore Node.js packages using 'npm ci'
              run: npm ci
            - name: Build Svelte Kit
              run: npm run build
            - name: Test Svelte Kit via Playwright
              run: npm test
